# Generated by Django 6.0.5 on 2026-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
