# Generated by Django 6.0.5 on 2026-06-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
