# Generated by Django 6.0.5 on 2026-06-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
