# Generated by Django 6.0.5 on 2026-06-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_order_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_source',
            new_name='order_type',
        ),
    ]
